Repository nextcloud/passman, pull requests merged in 2021-08, with the labels that each got.

#686 Fix passman json/csv file import; tiny ui improvements
  controller/translationcontroller.php
  css/app.css
  css/app.css.map
  js/app/controllers/credential.js
  js/app/controllers/edit_credential.js
  js/app/controllers/generic-csv-importer.js
  js/app/controllers/import.js
  js/importers/import-main.js
  js/importers/importer-passmanjson.js
  js/templates.js
  sass/app.scss
  sass/credentials.scss
  templates/views/partials/forms/settings/generic_csv_import.html
  templates/views/show_vault.html
Labels: needs testing

#695 fix showing Passman app icon in application header whether access is …
  lib/AppInfo/Application.php
Labels: bug, Needs Review

#706 Next release batch
  .jshintrc
  Gruntfile.js
  appinfo/database.xml
  appinfo/info.xml
  controller/admincontroller.php
  controller/translationcontroller.php
  css/app.css
  css/app.css.map
  css/bookmarklet.css
  css/bookmarklet.css.map
  js/app/controllers/bookmarklet.js
  js/app/controllers/credential.js
  js/app/controllers/edit_credential.js
  js/app/controllers/export.js
  js/app/controllers/generic-csv-importer.js
  js/app/controllers/import.js
  js/app/controllers/settings.js
  js/app/services/fileservice.js
  js/exporters/exporter-csv.js
  js/exporters/exporter-json.js
  js/exporters/exporter-main.js
  js/importers/import-main.js
  js/importers/importer-passmanjson.js
  js/templates.js
  lib/AppInfo/Application.php
  lib/Db/FileMapper.php
  lib/Migration/Version020308Date20210711121919.php
  lib/Migration/Version020308Date20210805164128.php
  lib/Service/FileService.php
  package.json
  sass/app.scss
  sass/bookmarklet.scss
  sass/credentials.scss
  sass/menu.scss
  sass/partials/tabs.scss
  templates/bookmarklet.php
  templates/main.php
  templates/public_share.php
  templates/views/edit_credential.html
  templates/views/partials/forms/settings/generic_csv_import.html
  templates/views/settings.html
  templates/views/share_credential.html
  templates/views/show_vault.html
Labels: next
